version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - vod-db-test:/app/db

    command: ["npm", "test"]

volumes:
  vod-db-test: