version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    depends_on:
      - redis
    volumes:
      - vod-db:/app/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  vod-db:
